/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?addon-style";
import _css2 from "./gamepadlib.css?addon-style";
import _asset from "./active.png";
import _asset2 from "./close.svg";
import _asset3 from "./cursor.png";
import _asset4 from "./dot.svg";
import _asset5 from "./gamepad.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "gamepadlib.css": _css2,
  "active.png": _asset,
  "close.svg": _asset2,
  "cursor.png": _asset3,
  "dot.svg": _asset4,
  "gamepad.svg": _asset5,
};
