/* generated by pull.js */
import _js from "./remove-backpack.js";
import _css from "./remove-backpack.css?addon-style";
export const resources = {
  "remove-backpack.js": _js,
  "remove-backpack.css": _css,
};
