/* generated by pull.js */
import _js from "./fix-share-the-love.js";
import _css from "./stageleft.css?addon-style";
export const resources = {
  "fix-share-the-love.js": _js,
  "stageleft.css": _css,
};
