/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _css2 from "!css-loader!./hover.css";
import _asset from "./loud.svg";
import _asset2 from "./quiet.svg";
import _asset3 from "./mute.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hover.css": _css2,
  "loud.svg": _asset,
  "quiet.svg": _asset2,
  "mute.svg": _asset3,
};
