/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./userstyle.css?addon-style";
import _css2 from "./hover.css?addon-style";
import _asset from "./loud.svg";
import _asset2 from "./mute.svg";
import _asset3 from "./quiet.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hover.css": _css2,
  "loud.svg": _asset,
  "mute.svg": _asset2,
  "quiet.svg": _asset3,
};
