/* generated by pull.js */
import _css from "./menu-icons.css?addon-style";
import _css2 from "./menu-labels.css?addon-style";
export const resources = {
  "menu-icons.css": _css,
  "menu-labels.css": _css2,
};
