/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./border.css?addon-style";
import _css2 from "./button.css?addon-style";
import _asset from "./backpack.svg";
export const resources = {
  "userscript.js": _js,
  "border.css": _css,
  "button.css": _css2,
  "backpack.svg": _asset,
};
