/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?addon-style";
import _asset from "./300cats.svg";
import _asset2 from "./cat.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "300cats.svg": _asset,
  "cat.svg": _asset2,
};
