/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?addon-style";
import _asset from "./assets/sv-gr.png";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "assets/sv-gr.png": _asset,
};
