/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "./toggle.svg";
import _asset2 from "./increment.svg";
import _asset3 from "./decrement.svg";
import _asset4 from "./settings.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "toggle.svg": _asset,
  "increment.svg": _asset2,
  "decrement.svg": _asset3,
  "settings.svg": _asset4,
};
