/* generated by pull.js */
import _css from "./sprites.css?addon-style";
import _css2 from "./costumes.css?addon-style";
import _css3 from "./sounds.css?addon-style";
export const resources = {
  "sprites.css": _css,
  "costumes.css": _css2,
  "sounds.css": _css3,
};
