/* generated by pull.js */
import _css from "!css-loader!./userstyle.css";
import _asset from "./icons/operators_icon.svg";
import _asset2 from "./icons/sound_icon.svg";
import _asset3 from "./icons/block_icon.svg";
import _asset4 from "./icons/looks_icon.svg";
import _asset5 from "./icons/events_icon.svg";
import _asset6 from "./icons/variables_icon.svg";
import _asset7 from "./icons/control_icon.svg";
import _asset8 from "./icons/motion_icon.svg";
import _asset9 from "./icons/sensing_icon.svg";
import _asset10 from "./icons/list_icon.svg";
export const resources = {
  "userstyle.css": _css,
  "icons/operators_icon.svg": _asset,
  "icons/sound_icon.svg": _asset2,
  "icons/block_icon.svg": _asset3,
  "icons/looks_icon.svg": _asset4,
  "icons/events_icon.svg": _asset5,
  "icons/variables_icon.svg": _asset6,
  "icons/control_icon.svg": _asset7,
  "icons/motion_icon.svg": _asset8,
  "icons/sensing_icon.svg": _asset9,
  "icons/list_icon.svg": _asset10,
};
