/* generated by pull.js */
const manifest = {
  "name": "Editor customizable colors",
  "description": "Customize colors in the editor. WIP. This reverts to the classic colours.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "settings": [
    {
      "name": "Accent color",
      "id": "accent",
      "type": "color",
      "default": "#59c059"
    },
    {
      "name": "Workspace color",
      "id": "workspace",
      "type": "color",
      "default": "#151515"
    },
    {
      "name": "UI color",
      "id": "ui",
      "type": "color",
      "default": "#202020"
    }
  ],
  "tags": [
    "theme",
    "beta",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
