/* generated by pull.js */
const manifest = {
  "name": "Editor customizable colors",
  "description": "Customize editor colors. The default options match those of the default AmpMod theme. You can also choose premade presets made by the AmpMod developers.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "settings": [
    {
      "dynamic": true,
      "name": "Base theme",
      "id": "base",
      "type": "select",
      "potentialValues": [
        {
          "id": "auto",
          "name": "Auto"
        },
        {
          "id": "light",
          "name": "Light"
        },
        {
          "id": "light-classic",
          "name": "Light (classic)"
        },
        {
          "id": "dark",
          "name": "Dark"
        }
      ],
      "default": "auto"
    },
    {
      "dynamic": true,
      "name": "Accent color",
      "id": "accent",
      "type": "color",
      "default": "#59c059"
    },
    {
      "dynamic": true,
      "name": "Workspace color",
      "id": "workspace",
      "type": "color",
      "default": "#f9f9f9"
    },
    {
      "dynamic": true,
      "name": "UI color",
      "id": "ui",
      "type": "color",
      "default": "#FAFAFA"
    },
    {
      "dynamic": true,
      "name": "Menu bar color",
      "id": "menubar",
      "type": "color",
      "default": "#ffffff"
    }
  ],
  "tags": [
    "theme",
    "beta",
    "ampmod",
    "new"
  ],
  "enabledByDefault": false,
  "presets": [
    {
      "name": "Soft pastel",
      "id": "pastel",
      "description": "A gentle pastel color theme.",
      "values": {
        "base": "light",
        "accent": "#FFB6C1",
        "workspace": "#FFF8F9",
        "ui": "#FFFDFE",
        "menubar": "#FFFFFF"
      }
    },
    {
      "name": "Fancy dark",
      "id": "fancyDark",
      "description": "Custom theme made by 8to16 on the forums.",
      "values": {
        "base": "dark",
        "accent": "#59c059",
        "workspace": "#241f31",
        "ui": "#3d3846",
        "menubar": "#FFB6C1"
      }
    }
  ]
};
export default manifest;
