/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?addon-style";
import _asset from "./folder.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "folder.svg": _asset,
};
