/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./userstyle.css?addon-style";
import _asset from "./icons/decrement.svg";
import _asset2 from "./icons/increment.svg";
import _asset3 from "./icons/off.svg";
import _asset4 from "./icons/on.svg";
import _asset5 from "./icons/settings.svg";
import _asset6 from "./icons/snap.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "icons/decrement.svg": _asset,
  "icons/increment.svg": _asset2,
  "icons/off.svg": _asset3,
  "icons/on.svg": _asset4,
  "icons/settings.svg": _asset5,
  "icons/snap.svg": _asset6,
};
